# Generated by Django 4.1 on 2022-08-07 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, choices=[('pre-payed', 'pre-payed'), ('miscellaneous', 'miscellaneous')], max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('amounts', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('APPR0VED', 'APPR0VED')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reimbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallets', models.CharField(blank=True, max_length=10000)),
                ('crypto', models.CharField(blank=True, choices=[('ETH', 'ETH'), ('USDT', 'USDT')], max_length=100)),
                ('upload', models.FileField(blank=True, upload_to='uploads/')),
                ('status', models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('APPR0VED', 'APPR0VED')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.user')),
            ],
        ),
    ]
